### ISSUE TITLE
question about the llama instruction code

### ISSUE THREAD

**Issue by yeontaek** [philschmid/deep-learning-pytorch-huggingface#28]
Hello. The qlora and flash attention code has been very helpful.

I noticed that the code worked fine in llam2 7b, but there seems to be a shape issue in 70b. Is that correct?

**Comment by philschmid** [comment]
Can you share the exact error you get?

**Comment by philschmid** [comment]
Does it work without flash attention?

**Comment by yeontaek** [comment]
Thank you. I'm currently testing the 13b model, and once that's done, I'll take a look and make adjustments.

**Comment by jaslatendresse** [comment]
Can you run this on a macbook pro m1 with 16 GB of RAM? I plan to use llama-2-7b-chat-hf...This is my last resort as nothing seems to work on my machine because nothing is compatible with M1.

**Comment by philschmid** [comment]
Not sure about M1, but i found this guide: https://gist.github.com/cedrickchee/e8d4cb0c4b1df6cc47ce8b18457ebde0
