### ISSUE TITLE
Chat Inference Code

### ISSUE THREAD

**Issue by samarthsarin** [philschmid/deep-learning-pytorch-huggingface#4]
Hi,

Just wanted to check after training my custom data model how should I use it as a chatbot to generate answers for questions asked by the user?
Can you please tell me what needs to be changed in inference part of the code?

Looking forward to your response

**Comment by philschmid** [comment]
Can you please share a bit more infomration? Which model have you trained? which data? Where are you trying to do? 

Transformers has a `conversational` pipeline for that: https://huggingface.co/docs/transformers/v4.26.1/en/main_classes/pipelines#transformers.Conversation which you could nicely combine with gradio: https://gradio.app/docs/#chatbot

**Comment by samarthsarin** [comment]
Hi. Thank you for your reply.
I have replicated your code as it is using the samsum dataset itself. I will have a look at the conversational pipline. However I am facing another issue where I am unable to load the model from my local file directory after training is completed. I don't want to push the model on the huggingface repo. I have the model saved in my local folder directory and want to load it as it is for my summarization and conversational task.

Here is the error screenshot.

![image](https://user-images.githubusercontent.com/40137295/218404954-c0bf2736-4399-4a8d-8408-b70ce9a6e73a.png)
![image](https://user-images.githubusercontent.com/40137295/218405030-704b07bf-d458-4781-ba7e-3e6ce158b976.png)

**Comment by samarthsarin** [comment]
Thank you for your reply. It worked for me. 
Closing this issue.
