### ISSUE TITLE
Target modules all-linear not found in the base model.

### ISSUE THREAD

**Issue by kassemsabeh** [philschmid/deep-learning-pytorch-huggingface#43]
Thank you for these excellent resources!

When running: [https://github.com/philschmid/deep-learning-pytorch-huggingface/blob/main/training/fine-tune-llms-in-2024-with-trl.ipynb](https://github.com/philschmid/deep-learning-pytorch-huggingface/blob/main/training/fine-tune-llms-in-2024-with-trl.ipynb) notebook. I get an error on this line of code:

`
peft_config = LoraConfig(
        lora_alpha=128,
        lora_dropout=0.05,
        r=256,
        bias="none",
        target_modules="all-linear",
        task_type="CAUSAL_LM",
)`

It gives this error:

`ValueError: Target modules all-linear not found in the base model. Please check the target modules and try again.
`

Any ideas?

**Comment by philschmid** [comment]
It seems like you are not having the up to date versions.

**Comment by kassemsabeh** [comment]
It works for:

```
# LoRA config
peft_config = LoraConfig(
        lora_alpha=128,
        lora_dropout=0.05,
        r=256,
        bias="none",
        target_modules=[
        "q_proj",
        "up_proj",
        "o_proj",
        "k_proj",
        "down_proj",
        "gate_proj",
        "v_proj"],
        task_type="CAUSAL_LM",
)
```
I do not have `peft == 0.7.1` as the latest version gave an error while installing.

**Comment by philschmid** [comment]
Can you use the commit which is in the sample

**Comment by kassemsabeh** [comment]
Running: `pip install git+https://github.com/huggingface/peft@4a1559582281fc3c9283892caea8ccef1d6f5a4f--upgrade` as in the sample gives the following error:

```
error: pathspec '4a1559582281fc3c9283892caea8ccef1d6f5a4f--upgrade' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q 4a1559582281fc3c9283892caea8ccef1d6f5a4f--upgrade did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q 4a1559582281fc3c9283892caea8ccef1d6f5a4f--upgrade did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by philschmid** [comment]
There was a missing whitespace. i fixed it, the command is 
`!pip install git+https://github.com/huggingface/peft@4a1559582281fc3c9283892caea8ccef1d6f5a4f --upgrade`

**Comment by kassemsabeh** [comment]
Thanks!
